parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Shared
  JDevelop\Erp\Shared\:
    resource: '../src/Shared/'
    exclude:
      - '../src/Shared/Infrastructure/Symfony/Kernel.php'

  # Company
  JDevelop\Erp\Company\:
    resource: '../src/Company/'

  JDevelop\Erp\Company\Domain\Repository\CompanyRepositoryInterface:
    class: JDevelop\Erp\Company\Infrastructure\Repository\DoctrineCompanyRepository

  # Resource
  JDevelop\Erp\Resource\:
    resource: '../src/Resource/'

  JDevelop\Erp\Resource\Domain\Repository\CompanyRepositoryInterface:
    class: JDevelop\Erp\Resource\Infrastructure\Repository\DoctrineCompanyRepository

  JDevelop\Erp\Resource\Domain\Repository\ResourceRepositoryInterface:
    class: JDevelop\Erp\Resource\Infrastructure\Repository\DoctrineResourceRepository
