parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Shared
  JDevelop\Erp\Shared\:
    resource: '../src/Shared/'
    exclude:
      - '../src/Shared/Infrastructure/Symfony/Kernel.php'

  # Company
  JDevelop\Erp\Company\:
    resource: '../src/Company/'

  JDevelop\Erp\Company\Domain\Repository\CompanyRepositoryInterface:
    class: JDevelop\Erp\Company\Infrastructure\Repository\DoctrineCompanyRepository

  # Resource
  JDevelop\Erp\Resource\:
    resource: '../src/Resource/'

  JDevelop\Erp\Resource\Domain\Repository\CompanyRepositoryInterface:
    class: JDevelop\Erp\Resource\Infrastructure\Repository\DoctrineCompanyRepository

  JDevelop\Erp\Resource\Domain\Repository\ResourceRepositoryInterface:
    class: JDevelop\Erp\Resource\Infrastructure\Repository\DoctrineResourceRepository

  # Availability
  JDevelop\Erp\Availability\:
    resource: '../src/Availability/'

  JDevelop\Erp\Availability\Domain\Repository\ResourceRepositoryInterface:
    class: JDevelop\Erp\Availability\Infrastructure\Repository\DoctrineResourceRepository

  JDevelop\Erp\Availability\Domain\Repository\WorkScheduleRepositoryInterface:
    class: JDevelop\Erp\Availability\Infrastructure\Repository\DoctrineWorkScheduleRepository

  JDevelop\Erp\Availability\Domain\Repository\PublicHolidayRepositoryInterface:
    class: JDevelop\Erp\Availability\Infrastructure\Repository\InMemoryPublicHolidayRepository

  # Customer
  JDevelop\Erp\Customer\:
    resource: '../src/Customer/'

  JDevelop\Erp\Customer\Domain\Repository\CompanyRepositoryInterface:
    class: JDevelop\Erp\Customer\Infrastructure\Repository\DoctrineCompanyRepository

  JDevelop\Erp\Customer\Domain\Repository\CustomerRepositoryInterface:
    class: JDevelop\Erp\Customer\Infrastructure\Repository\DoctrineCustomerRepository

  # Contract
  JDevelop\Erp\Contract\:
    resource: '../src/Contract/'

  JDevelop\Erp\Contract\Domain\Repository\CompanyRepositoryInterface:
    class: JDevelop\Erp\Contract\Infrastructure\Repository\DoctrineCompanyRepository

  JDevelop\Erp\Contract\Domain\Repository\CustomerRepositoryInterface:
    class: JDevelop\Erp\Contract\Infrastructure\Repository\DoctrineCustomerRepository
