parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Shared
  JDevelop\Erp\Shared\:
    resource: '../src/Shared/'
    exclude:
      - '../src/Shared/Infrastructure/Symfony/Kernel.php'

  # Company
  JDevelop\Erp\Company\:
    resource: '../src/Company/'
